import Link from 'next/link';

export default function HomePage() {
  return (
    <div className="flex flex-col items-center justify-center min-h-[80vh] px-6">
      {/* Hero Section */}
      <section className="text-center max-w-3xl">
        <div className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white/60 px-4 py-1.5 text-sm text-slate-500 mb-8 shadow-sm">
          ⚡ Automated Legal Document Generator
        </div>
        <h1 className="text-5xl sm:text-6xl font-bold tracking-tight text-slate-900 leading-[1.1] mb-6">
          Legal docs for your{' '}
          <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
            Micro-SaaS
          </span>
          , instantly.
        </h1>
        <p className="text-lg sm:text-xl text-slate-600 max-w-2xl mx-auto mb-10 leading-relaxed">
          Paste your <code className="rounded bg-slate-200 px-2 py-0.5 text-sm font-mono text-slate-800">package.json</code>{' '}
          and get tailored legal clauses — privacy policies, terms of service, liability limitations, and more — based on
          your actual dependencies and API routes.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <Link
            href="/generate"
            className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-8 py-4 text-base font-semibold text-white shadow-lg shadow-blue-200 hover:bg-blue-700 transition-all"
          >
            Generate Documents →
          </Link>
          <a
            href="#how-it-works"
            className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-8 py-4 text-base font-semibold text-slate-700 hover:bg-slate-50 transition-all"
          >
            How It Works
          </a>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="mt-32 max-w-5xl w-full">
        <h2 className="text-3xl font-bold text-center mb-16">How It Works</h2>
        <div className="grid md:grid-cols-3 gap-8">
          {steps.map((step, i) => (
            <div key={step.title} className="relative rounded-2xl bg-white p-8 shadow-sm border border-slate-200">
              <span className="absolute -top-4 -left-4 flex h-10 w-10 items-center justify-center rounded-full bg-blue-600 text-white font-bold text-lg shadow-md">
                {i + 1}
              </span>
              <h3 className="text-xl font-semibold mb-3 mt-2">{step.title}</h3>
              <p className="text-slate-600 leading-relaxed">{step.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="mt-32 max-w-5xl w-full">
        <h2 className="text-3xl font-bold text-center mb-16">What You Get</h2>
        <div className="grid md:grid-cols-2 gap-6">
          {features.map((feature) => (
            <div key={feature.title} className="flex items-start gap-4 rounded-xl bg-white p-6 shadow-sm border border-slate-200">
              <span className="text-2xl flex-shrink-0">{feature.icon}</span>
              <div>
                <h3 className="font-semibold text-lg mb-1">{feature.title}</h3>
                <p className="text-slate-600 text-sm leading-relaxed">{feature.description}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="mt-32 mb-8 text-center text-sm text-slate-400">
        <p>AutoLegal MicroSaaS — Generated by the Antigravity Kit.</p>
        <p className="mt-1">
          This tool provides drafts only. Always consult a qualified attorney for legal advice.
        </p>
      </footer>
    </div>
  );
}

const steps = [
  {
    title: 'Paste Your Package.json',
    description:
      'Copy your project\'s package.json into the editor. AutoLegal scans all dependencies and devDependencies.',
  },
  {
    title: 'AI-Powered Analysis',
    description:
      'Our engine maps dependencies to legal requirements — Stripe means payment terms, NextAuth means privacy policy, and more.',
  },
  {
    title: 'Download & Use',
    description:
      'Get a complete legal document package tailored to your stack. Markdown formatted, ready to customize.',
  },
];

const features = [
  {
    icon: '🛡️',
    title: 'Privacy Policy',
    description: 'Auto-generated based on data-collecting dependencies like analytics, auth, and databases.',
  },
  {
    icon: '📜',
    title: 'Terms of Service',
    description: 'Covers user rights, liability limitations, and intellectual property tailored to your SaaS.',
  },
  {
    icon: '🔒',
    title: 'Data Security Clauses',
    description: 'Elevated security terms when sensitive routes (auth, payments) are detected in your API.',
  },
  {
    icon: '⚖️',
    title: 'Risk Assessment',
    description: 'Automatic risk level classification — low, medium, or high — based on your dependency profile.',
  },
];
